/**
 * @fileoverview gRPC-Web generated client stub for sms
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.23.3
// source: sms_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var common_pb = require('./common_pb.js')

var sms_pb = require('./sms_pb.js')
const proto = {};
proto.sms = require('./sms_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.sms.SmsServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.sms.SmsServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.common.StringValue,
 *   !proto.common.StringValue>}
 */
const methodDescriptor_SmsService_send_otp = new grpc.web.MethodDescriptor(
  '/sms.SmsService/send_otp',
  grpc.web.MethodType.UNARY,
  common_pb.StringValue,
  common_pb.StringValue,
  /**
   * @param {!proto.common.StringValue} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  common_pb.StringValue.deserializeBinary
);


/**
 * @param {!proto.common.StringValue} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.common.StringValue)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.common.StringValue>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sms.SmsServiceClient.prototype.send_otp =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sms.SmsService/send_otp',
      request,
      metadata || {},
      methodDescriptor_SmsService_send_otp,
      callback);
};


/**
 * @param {!proto.common.StringValue} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.common.StringValue>}
 *     Promise that resolves to the response
 */
proto.sms.SmsServicePromiseClient.prototype.send_otp =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sms.SmsService/send_otp',
      request,
      metadata || {},
      methodDescriptor_SmsService_send_otp);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sms.VerifyOtpRequest,
 *   !proto.common.Empty>}
 */
const methodDescriptor_SmsService_verify_otp = new grpc.web.MethodDescriptor(
  '/sms.SmsService/verify_otp',
  grpc.web.MethodType.UNARY,
  sms_pb.VerifyOtpRequest,
  common_pb.Empty,
  /**
   * @param {!proto.sms.VerifyOtpRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  common_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.sms.VerifyOtpRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.common.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.common.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sms.SmsServiceClient.prototype.verify_otp =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sms.SmsService/verify_otp',
      request,
      metadata || {},
      methodDescriptor_SmsService_verify_otp,
      callback);
};


/**
 * @param {!proto.sms.VerifyOtpRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.common.Empty>}
 *     Promise that resolves to the response
 */
proto.sms.SmsServicePromiseClient.prototype.verify_otp =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sms.SmsService/verify_otp',
      request,
      metadata || {},
      methodDescriptor_SmsService_verify_otp);
};


module.exports = proto.sms;

